' --- Sprites ---

sprite $rsa [66x24/16z] {
TLI5eiCm4EfPBjt__--J2eCAqqOuWSGSi4NXMMDK-dA56IyTAs7GJAr0Xn3qtz1a1a6UuvD7fsIm3SKB0sPwsrYPzVyFXNntD3qZWc_R40TXlAI88vGh0nwE
ElA_ASiJq9zc1Ybnd0mIMLFm_ozZ1k3aJcgV8hOb0pa-vO0-j3IGD8fzdXX4wQ1gPzvSTYJNA9COB2Po9qELNzsK1zCg3F7vN4JoXfz2tOHgKdBeVJ5dRNKQ
Sx3SXOvEOJ1uMX0j5AGYF8S-51OghB_RYfoKst_f9BgWGCcw10zWG6KA65HMI49WW5BF34X6TJ5c4ADPg0T2FG1X1Z5eCnj-D9pvbkC6HZ28M76SuExT4a5P
Qt851bKe7Ywk8JSJLX637grikNzLIjNv7PvPkEpVyGi
}

sprite $oracle [85x48/16z] {
xP67bGGX34D7E83LVy77OfwFYmqiVyECdeH8ppjokLmk5zcqL4K5eAZtLcu62Xp3O2n2fpwax7Xmx5ODRXH170iRtFXKWz7T9kw3D83qr9tCjJj9Msz6ZcNQ
rB7iHCcnXs768awBqbWByAmIKhE_aLhXinIHqLBdoHZzADMr5Gmgd0FBFiB7zfNzC1e3f-JuB6rZhSiui9Sos9vVL-gCelrHgi68u5hTr99dWFzA2_zp-n9a
X6DTf8keQB33QR-Kra4L5WCb92WjYFNco7Z0cAYGykkP8gX7AGR3pVJrxQG1NDaMn-RjXJEQaJt3gWYQBM4goz0KhrPd4JRrAitPsjEFQ-rqM71Z62pQ8sLu
BbOqaILLdqHLCRzLca8qcRjGFGQMWUVTk5mkbyi7
}

sprite $internet [39x30/16z] {
fP85ik0m34CRC4d9_Q-xPUxIrr3XZIp3y3EbN4fEVu2AOvRbtpbvYrfoBeAcR_z7ZLR4Rb8PwSQ8WmmL-kbh1YvS3bWjLT7yyZt1pc-CfL8gwTPEAyTBuBDx
zoDN_swzSArZeErZVV0PTGa9oMc152JgRGGXrrZ9ARbOqnTCsXvUMRrHfPTdKJ_cGdDKfOHViJ9Qdg9qdLuib6TCa1vO6KlVi6KDeNlMRgmf6QoTpPQnAROn
HcS3mCRknusqfLhcQXTUDmbqzzATrsNvQyYH4jXwDjJJ3T1antAGx3PaDVJ8buiCv0rBPIfgO-RGbtlOtHp0wFQXtKtDZ7_4SW3yTXkWQLEERqmPcy3wYQKg
kyhmN_e5
}

sprite $api_gateway [33x30/16z] {
fL854WCn23mWdeNx_syxAKdToqW465ZP7WQdadXx7b4Lgl5fNgmASR7mhA22ne7s94_8npE3VYnWUAO_6H5XhvQKfYtSmPHSiXp7PzDqHnIt7Hqxc99fNZqf
HvfBTqGYYW2qoiodCGI-H5O_-M9gii8aJKSzeSpVZDDOD6yPAJdr1UlLe-rnSdvRq3nMGO4JUrfCrjweus0_glByrN1UClkINjV5AOGMNWixp3bRhPQg5fp7
HUu5bvHQRvd6hHZ6VXppjIU9Q7LshHBnmfCqvPRwr9ECjvuiVtfoQzqzsRSd4ORONEm93BTBLqrFyoUJZZW
}

sprite $service_bus [33x30/16z] {
XT55eaGX34JH0b91mlwt-wNxkIHdoiM1MD5DmfDMPT6PyrDGi52oMNC303AJ7o3F801R4616GIj1e0m2lWMbE5iKMsIWcralb-0gztuEykt3n4v1uW8RhLlm
OXu3sG-vgN9P8IUSI7ryg5rfGK0D0aj-C7GvgorKsUn0S4N2aGabcF5gaDGEnx3HuNePz_q2
}

sprite $bash [78x57/16z] {
xTI7ZciX30JGEwOQxF__tIUSXhRXF5ZLTPhgkJEKNBy-VuCpIgeb7CAGE-VIAXtWaBZGzBirn1oU6LlUM4GhEGEXSS1_Ua3yK6wkYpVFGR2IdzEMYNAJyohD
WzT3lEXKylCaBk6zdQoqE3Lm9mkILezh5UvayLeE9wSMo_g1kLGuTtCPBOb8XuzRxLXW4LKveb4TbieHBNKL7MzVKvZsGp1HUvk6ZMnKckWDssyQsd3kiwcX
s4uUqP2w4KSq2pPbspkzSK23qXDQaI5rFTEKHKLBdfhgXbP7pumWUaGJaKQX67F3jZJj8T-fszvktDCgqi2YuwLgOD_Ane2bUtTFyvUQPCBLxZNVQ9hoPyq0
1e-kNGVPF1ek1ARFcWwDkaXlj_NBpgR8BNpMEXSQcr6ROOqCStNj-TFfRRYYYBGkSiFS6eWvVBXPlSOaOfJsT1dcumY8jRuyL1MHRXrLUYQuUzet0RcNEPiE
S7muJ9O_7zLdNNvTg0JWWbUPL-zPjwfbqr5oQ1FdTeaGMu5bivQLo4f-mjnrkKNxxzLHSd4kLXniTsCMiP9cRNb4iJ8xJeMpBXbgrX7FIXuV8u_Ft_m3
}

sprite $c_plus_plus [56x58/16z] {
bPI7jeOW38E1Bi3tVzux_i4XGgtc3ESdD4rDheeefSVAslvavI4cxIFD3oXka-GkHRMX-0vLh2sgTCEELR51qbnf3knm9QuTaJYqeohJdrZiqY2qe_9S2vbh
aE2JQvCrRmkZRLFhQX1kmtCR-vfFD_HcPcjA5R6RO4xp9eFPyhXer6pFnQ7VSeRli9efPwXmovLjfwr0Ve5RbYiGPiZlmX5W26BIa8FoKGIjGyuWKg469yvo
OpFZB0F7uFPzZlnjLlilmgnEPuChkpJXepAThTmOa7xqHvnzg7-zI67-Bvkb2TFdR5EV36oGw8lJXp9H_s3tEUnxFL1_e8Xylo_gvOoEarIzlE0OAM8Dfk7C
QNB01d_GXMimsNrWwiujEZgwyLfBS_IVw4TEg9pJIQsVkJuAMOHbzvdhK8edcXAKqvmEliBA78ISx7KQWwNF2Vh_p2pnC5fUov372YOwIQ3l10HBqln2Pyp7
K1TSaoTgCLqmoa8lDXV1gRAbZ6n7g5gsJjThgfDhThkW9Fb2WpmxWau5NOqDQYMcq23iSopgKM9_0G
}

sprite $springboot [111x48/16z] {
xPS7bk0e34HH-dN_4symzMmcjZT7JMYYFWL2kDTh-z_oJwK1_s9SJgw_hKNQR16V3uZFQj-sECjV6vc8pwtFIGqm6IiXeq3CvGSo6cerxHg2sjCAe6EDJcyr
qWsK1FPdYs7tpsfKBM6VAMO45OWeD2sGw3qD2IZipDu46AW7MylMeZCRiNehhqOYLx4j5cBL9Ws2N6kG9ck4uC4LCamoIU9OqRYOiHhBJj148jU1Q8cEtTUN
szh-WVFWDaTSfLsJe6-SwX6Afm5PY5dBk49RHQDP8tMikxfieuCq67pLqWmG5IxsSmHLWZnmPYTC0Fa82jCAqxZwOwnDJxJ406BoKfUUs50fiHwSl9OK4tCp
0cwSequpWhZgCu3nsxA1Azv57JZhCQvHFtBWIvp5YRvsvy8JgwnupYorFJudAhBWL7VZ135wDXDki2xQ1kqmtAlGVL_ZyT-2l5rcIdFYwEVi6lV5tEfwuoOk
WjNrxe1zn3cJtlPeHqsKWvrJdTIFdFHToa7oJVAcvIuQHstPRDc5e7kqbuoOGOAhQupJgUvgRYJW2BezJMtt5quxH4h2nTvJD7c5IYFi8J_3oSaIjUD2OlQY
h4ZRfM3ZCFSurLKzqnax72DgfdFjZbWkr8fswt8XUhep1iPn0jA4YyI50wSyHyjXRG4lB6RYicR7Q269Isd2hKvSHrxEBHCdJhp55MXc1dcBHWw7VT5a78Xn
vhRIs-ezRlL883mbPbUmRo1MpDd4vxkPOx5lBB9dPiepdbTpfK-nTvlASOnGhj_37Ek-om0OBnJUQlV-BXOWjEEcZ4D2pDK9-Cx_FiHyTZD6vY4HljiuQDue
hEdrWGqRKclbR9GZAG1PURywlnVRdbYHKwa4J2q7oXQ-vXqEVOHpxcBVvQXnTeh67R47PNQtcTbFS4UrsnDK7yfpT33v-MUi46fdha50kGRQvHevQIINnKjv
yeAtIF0Y_6uWPXp2WXd0vpqz-ri0mNo0yp3yKcHczI1n9fGHPEpdEO1S_aveKH41oXM8V16_5lByBu4u5jlt0qAaTdaWmeI-rWMl4i8OWY5VVcUEPQBdQsiW
muGIyngNbcLD68RzFhX04mKR9-B6eNakmikxZh1PgHTxVtIdD960qHSkDxhUum9PeCsrEg9NdSKbRAIEt7jQKcVKdUGhymMl-98c9WxSypYanqmUYROSl_16
NWyWEAtZ3DuU_v9WdilH05Dk5_FotVt2pkwCQuGNuAAxZdQN_dNsl_q8
}

sprite $springboot2 [48x48/16z] {
pPHfqlCW38DBlEZ-9_uMz0mCG_g_UXT28sJBTldyD9wuyPsT_OhyGYzrws9BglTS-YkUDtwZVWVeVarUxLyMmvlRmf2LOA8hTXgNMPJvY-0e8dMRHMak_-HY
xQJRSf6A5yq4PHzUpW2nkEDVABKZUkC8YfTQgiVSoFoQYuMEcYQX9_tnkz5YYrZkMWfZuVVmEP_qOzUqd8pZpr2Sym74Latnv9hP745TbiISQme5rV0Ryd7T
npb6qSQCn-FscVxGY5LBTeF86E6nc3ioq4pPV8gDAwoaw9d2SyoChIJGTmTDCIbNC6dntOXQLf1iJOjXwpHGafQQg4cvOpeikXzb7RY8h6_FxhVEAfhB43me
C4B3RXcVQjY2WQ37qGs3GLiHNYqSvBk_0WwEsYZvD7Gi8RS6ph_1W6YtFsdd6hUZuOy5CZFy64TkOAM8vaPItECAeeDShizvo_32jLnm_evIyJWfc8pcWQ0c
B3iBdgdbnjPQ5wT1uElsXmgRm-oesu4YC88xdcjvOP3i2TAZbbUftw7yl06JTm2RlJ3A3WzmoRqZiYvaV7uPVm4
}
